
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 6.3 EDK_Gmm.10
* DO NOT EDIT.
*
* Copyright (c) 2004 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver parameters
*
*******************************************************************/

#define STDIN_BASEADDRESS 0x02604000
#define STDOUT_BASEADDRESS 0x03E00100

/******************************************************************/

#define XPAR_LMB_BRAM_IF_CNTLR_DS_BASEADDR 0x00000000
#define XPAR_LMB_BRAM_IF_CNTLR_DS_HIGHADDR 0x00007FFF
#define XPAR_LMB_BRAM_IF_CNTLR_IS_BASEADDR 0x00000000
#define XPAR_LMB_BRAM_IF_CNTLR_IS_HIGHADDR 0x00007FFF

/******************************************************************/

#define XPAR_XEMC_NUM_INSTANCES 1
#define XPAR_SRAM_256KX32_FLASH_2MX32_BASEADDR 0x03C00000
#define XPAR_SRAM_256KX32_FLASH_2MX32_HIGHADDR 0x03C001FF
#define XPAR_SRAM_256KX32_FLASH_2MX32_DEVICE_ID 0
#define XPAR_SRAM_256KX32_FLASH_2MX32_NUM_BANKS_MEM 2

/******************************************************************/

#define XPAR_SRAM_256KX32_FLASH_2MX32_MEM0_BASEADDR 0x02800000
#define XPAR_SRAM_256KX32_FLASH_2MX32_MEM0_HIGHADDR 0x028FFFFF
#define XPAR_SRAM_256KX32_FLASH_2MX32_MEM1_BASEADDR 0x03000000
#define XPAR_SRAM_256KX32_FLASH_2MX32_MEM1_HIGHADDR 0x037FFFFF

/******************************************************************/

#define XPAR_SDRAM_8MX32_BASEADDR 0x01000000
#define XPAR_SDRAM_8MX32_HIGHADDR 0x01FFFFFF

/******************************************************************/

#define XPAR_XUARTLITE_NUM_INSTANCES 2
#define XPAR_RS232_P160_BASEADDR 0x03E00100
#define XPAR_RS232_P160_HIGHADDR 0x03E001FF
#define XPAR_RS232_P160_DEVICE_ID 0
#define XPAR_RS232_P160_BAUDRATE 2400
#define XPAR_RS232_P160_USE_PARITY 0
#define XPAR_RS232_P160_ODD_PARITY 0
#define XPAR_RS232_P160_DATA_BITS 8
#define XPAR_RS232_BASEADDR 0x02604000
#define XPAR_RS232_HIGHADDR 0x026040FF
#define XPAR_RS232_DEVICE_ID 1
#define XPAR_RS232_BAUDRATE 1200
#define XPAR_RS232_USE_PARITY 0
#define XPAR_RS232_ODD_PARITY 0
#define XPAR_RS232_DATA_BITS 7

/******************************************************************/

#define XPAR_XGPIO_NUM_INSTANCES 3
#define XPAR_PUSH_BUTTONS_3BIT_BASEADDR 0x02C80000
#define XPAR_PUSH_BUTTONS_3BIT_HIGHADDR 0x02C801FF
#define XPAR_PUSH_BUTTONS_3BIT_DEVICE_ID 0
#define XPAR_PUSH_BUTTONS_3BIT_INTERRUPT_PRESENT 0
#define XPAR_PUSH_BUTTONS_3BIT_IS_DUAL 0
#define XPAR_LEDS_4BIT_BASEADDR 0x02200000
#define XPAR_LEDS_4BIT_HIGHADDR 0x022001FF
#define XPAR_LEDS_4BIT_DEVICE_ID 1
#define XPAR_LEDS_4BIT_INTERRUPT_PRESENT 0
#define XPAR_LEDS_4BIT_IS_DUAL 0
#define XPAR_DIP_SWITCHES_8BIT_BASEADDR 0x03A00000
#define XPAR_DIP_SWITCHES_8BIT_HIGHADDR 0x03A001FF
#define XPAR_DIP_SWITCHES_8BIT_DEVICE_ID 2
#define XPAR_DIP_SWITCHES_8BIT_INTERRUPT_PRESENT 0
#define XPAR_DIP_SWITCHES_8BIT_IS_DUAL 0

/******************************************************************/

