
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 6.3 EDK_Gmm.10
* DO NOT EDIT.
*
* Copyright (c) 2004 Xilinx, Inc.  All rights reserved. 
* 
* Description: Exception Handler Table for MicroBlaze Processor
*
*******************************************************************/

#include "microblaze_exceptions_i.h"
#include "xparameters.h"


