
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 6.3 EDK_Gmm.10
* DO NOT EDIT.
*
* Copyright (c) 2004 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartlite.h"

/*
* The configuration table for devices
*/

XUartLite_Config XUartLite_ConfigTable[] =
{
	{
		XPAR_RS232_P160_DEVICE_ID,
		XPAR_RS232_P160_BASEADDR,
		XPAR_RS232_P160_BAUDRATE,
		XPAR_RS232_P160_USE_PARITY,
		XPAR_RS232_P160_ODD_PARITY,
		XPAR_RS232_P160_DATA_BITS
	},
	{
		XPAR_RS232_DEVICE_ID,
		XPAR_RS232_BASEADDR,
		XPAR_RS232_BAUDRATE,
		XPAR_RS232_USE_PARITY,
		XPAR_RS232_ODD_PARITY,
		XPAR_RS232_DATA_BITS
	}
};
