
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 6.3 EDK_Gmm.10
* DO NOT EDIT.
*
* Copyright (c) 2004 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xemc.h"

/*
* The configuration table for devices
*/

XEmc_Config XEmc_ConfigTable[] =
{
	{
		XPAR_SRAM_256KX32_FLASH_2MX32_DEVICE_ID,
		XPAR_SRAM_256KX32_FLASH_2MX32_BASEADDR,
		XPAR_SRAM_256KX32_FLASH_2MX32_NUM_BANKS_MEM
	}
};
