
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 6.3 EDK_Gmm.10
* DO NOT EDIT.
*
* Copyright (c) 2004 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_PUSH_BUTTONS_3BIT_DEVICE_ID,
		XPAR_PUSH_BUTTONS_3BIT_BASEADDR,
		XPAR_PUSH_BUTTONS_3BIT_INTERRUPT_PRESENT,
		XPAR_PUSH_BUTTONS_3BIT_IS_DUAL
	},
	{
		XPAR_LEDS_4BIT_DEVICE_ID,
		XPAR_LEDS_4BIT_BASEADDR,
		XPAR_LEDS_4BIT_INTERRUPT_PRESENT,
		XPAR_LEDS_4BIT_IS_DUAL
	},
	{
		XPAR_DIP_SWITCHES_8BIT_DEVICE_ID,
		XPAR_DIP_SWITCHES_8BIT_BASEADDR,
		XPAR_DIP_SWITCHES_8BIT_INTERRUPT_PRESENT,
		XPAR_DIP_SWITCHES_8BIT_IS_DUAL
	}
};
